name=every
version=0.8.0
author=Funny Pedrei <funny.pedrei@platynum.ch>
maintainer=Funny Pedrei <funny.pedrei@platynum.ch>
sentence=A library that executes a piece of code at defined intervals.
paragraph=Depends on the internal arduino millis functions, only.
category=Timing
url=https://github.com/fpedrei/every/
architectures=*
